[book]
authors = ["slashformotion"]
language = "en"
multilingual = false
src = "src"
title = "slashformotion's stuff"


[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
no-section-label = false
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/slashformotion/mystuff"
# site-url = "/"
# cname = "myproject.rs"
# input-404 = "not-found.md"

[output.html.search]
    enable = true            # enables the search feature
    limit-results = 30       # maximum number of search results
    teaser-word-count = 30   # number of words used for a search result teaser
    use-boolean-and = true   # multiple search terms must all match
    boost-title = 2          # ranking boost factor for matches in headers
    boost-hierarchy = 1      # ranking boost factor for matches in page names
    boost-paragraph = 1      # ranking boost factor for matches in text
    expand = true            # partial words will match longer terms
    heading-split-level = 3  # link results to heading levels
    copy-js = true 

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 3       # the depth to start folding

[output.html.redirect]
# "/appendices/bibliography.html" = "https://rustc-dev-guide.rust-lang.org/appendix/bibliography.html"
# "/other-installation-methods.html" = "../infra/other-installation-methods.html"

# [output.pdf]
# ## Set for auto-retrying if failed to generate PDF.
# # trying-times = 1
# ## This backend only support latest Chromium based browsers, not Safari and Firefox currently.
# ## If needed, please specify the full path.
# ## If you specify the wrong binary, chances are that there will be a timeout error.
# # browser-binary-path = ""
# ## Assign the static hosting site url so that relative links outside the book can be fixed.
# # static_site_url = "https://rust-lang.github.io/mdBook"
# ## Check Chrome Devtools Protocol Docs for the explanation of the following params:
# ## https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
# landscape = false
# display-header-footer = true
# print-background = true
# scale = 1
# paper-width = 8
# paper-height = 10
# margin-top = 0.5
# margin-bottom = 0.5
# margin-left = 0.5
# margin-right = 0.5
# page-ranges = ""
# ignore-invalid-page-ranges = false
# header-template = "<h3 style='font-size:8px; margin-left: 48%' class='title'></h3>"
# footer-template = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"
# prefer-css-page-size = true